"use client";
import {partCategories} from './part-categories';
import VehicleVisual from './vehicle-visual';
import {VehicleInfo} from './vehicle-search';
import {useEffect,useState} from 'react';
import {Search,CarFront,Disc3,Wrench,Wind,Droplets,BatteryCharging,ArrowUpRight,Plus,MapPin,ChevronRight} from 'lucide-react';
import VehicleFinder,{SearchSession} from './vehicle-finder';
import {RecordItem} from './data';
import {partSuggestions,searchIntent} from './search-intent';
type Props={records:RecordItem[];signedIn:boolean;selectedCar:string;selectCar:(id:string)=>void;save:(kind:string,data:any)=>Promise<any>;onSearch:(s:SearchSession)=>void;navigate:(s:string)=>void};
const icons=[Disc3,Wrench,CarFront,Wind,Droplets,BatteryCharging];
const groups=partCategories.map((g,i)=>({...g,icon:icons[i]}));
export default function HomeWorkbench(p:Props){
 const [categoryFilter,setCategoryFilter]=useState('');
 const [lookupVin,setLookupVin]=useState('');
 const [preview,setPreview]=useState<VehicleInfo|null>(null);
 const [text,setText]=useState(''),[group,setGroup]=useState(0),[command,setCommand]=useState<{text:string;id:number}|undefined>(),[help,setHelp]=useState(false);
 const cars=p.records.filter(r=>r.kind==='car');const active=cars.find(c=>c.id===p.selectedCar);const history=p.records.filter(r=>r.kind==='searchHistory');const offers=history[0]?.data.results||[];
 useEffect(()=>{setLookupVin('');},[active?.id]);
 function submit(value:string){if(!value.trim())return;if(searchIntent(value).kind==='service'){p.navigate('service');return;}setText(value);setCommand({text:value,id:Date.now()});setTimeout(()=>document.getElementById('finder-workspace')?.scrollIntoView({behavior:'smooth',block:'start'}),80);}
 return <div className="home-workbench"><form className="unified-search" onSubmit={e=>{e.preventDefault();submit(text);}}><Search size={21}/><input aria-label="Пошук VIN, деталі або симптомів" list="motorna-search-suggestions" value={text} onChange={e=>setText(e.target.value)} placeholder="VIN, назва деталі, OEM або що сталося з авто…" maxLength={1000}/><datalist id="motorna-search-suggestions">{partSuggestions.map(v=><option key={v} value={v}/>)}<option value="СТО поруч"/></datalist><button className="primary">Знайти <ArrowUpRight size={17}/></button></form>
 <div className="dashboard-hero"><div><span className="eyebrow">ВАШ АВТОМОБІЛЬ. ВАШ ПРОСТІР.</span><h1>Усе для вашого авто.<br/><span>В одному місці.</span></h1><p>Знайдіть деталь, розберіться із симптомами<br/>та оберіть сервіс поруч.</p><button className="text-btn" onClick={()=>setHelp(!help)}>Як це працює <ChevronRight size={16}/></button>{help&&<ol className="onboarding"><li>Знайдіть авто за VIN або оберіть у гаражі.</li><li>Введіть деталь чи опишіть проблему.</li><li>Порівняйте знайдені пропозиції.</li><li>Оберіть СТО та зателефонуйте.</li></ol>}{cars.length>0&&<label className="hero-car-picker">Автомобіль для підбору<select className="input" value={p.selectedCar} onChange={e=>{setLookupVin('');setPreview(null);if(command&&searchIntent(command.text).kind==='vin')setCommand(undefined);p.selectCar(e.target.value);}}><option value="">Додати авто за VIN</option>{cars.map(c=><option value={c.id} key={c.id}>{c.data.name} · {c.data.year}</option>)}</select></label>}</div><VehicleVisual vin={lookupVin||preview?.vin||active?.data.vin} make={preview?.make||active?.data.make} model={preview?.model||active?.data.model} year={String(preview?.year||active?.data.year||'')} fields={lookupVin&&lookupVin!==preview?.vin?[]:preview?.fields||active?.data.specifications||[]} name={lookupVin&&lookupVin!==preview?.vin?'Автомобіль за VIN '+lookupVin:preview?[preview.make,preview.model,preview.year].join(' '):active?.data.name} onSelect={setGroup}/></div>
 <div className="category-strip" aria-label="Категорії деталей">{groups.map((g,i)=><button key={g.name} className={'category-color-'+i+(group===i?' active':'')} onClick={()=>{setGroup(i);setCategoryFilter('');}} aria-controls="category-details" aria-pressed={group===i}><g.icon size={23}/><span>{g.name}</span></button>)}</div><section id="category-details" className="category-details" aria-label={'Деталі: '+groups[group].name}><div className="section-top"><div><h2>{groups[group].name}</h2><p>{groups[group].description}</p></div><span>{groups[group].sections.reduce((n,s)=>n+s.parts.length,0)} видів деталей</span></div><p className="fine">{active?'Пошук для '+active.data.name:'Оберіть деталь, а потім підтвердьте авто за VIN.'} · Наявність вузлів і сумісність залежать від комплектації.</p><input className="input category-filter" aria-label="Знайти деталь у категорії" placeholder="Знайти у цій категорії…" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}/><div className="category-sections">{groups[group].sections.map(section=>{const visible=section.parts.filter(part=>part.toLocaleLowerCase('uk-UA').includes(categoryFilter.trim().toLocaleLowerCase('uk-UA')));return visible.length>0&&<div key={section.name}><h3>{section.name}</h3><div className="category-options">{visible.map(part=><button key={part} onClick={()=>submit(part)}>{part}<ArrowUpRight size={14}/></button>)}</div></div>;})}</div>{!groups[group].sections.some(s=>s.parts.some(part=>part.toLocaleLowerCase('uk-UA').includes(categoryFilter.trim().toLocaleLowerCase('uk-UA'))))&&<p role="status">У цій категорії такого пункту немає. <button className="text-btn" onClick={()=>submit(categoryFilter)}>Шукати «{categoryFilter}»</button></p>}<div className="category-symptoms"><h3>Не знаєте, яка деталь потрібна?</h3><p>Оберіть симптом — розберемо можливі причини.</p><div className="category-options">{groups[group].symptoms.map(symptom=><button key={symptom} onClick={()=>submit(symptom)}>{symptom}<ChevronRight size={14}/></button>)}</div><button className="text-btn" onClick={()=>p.navigate('service')}>Знайти СТО поруч <ArrowUpRight size={15}/></button></div></section>
 <div className="dashboard-lower"><section className="dashboard-card"><div className="section-top"><h2>Мій гараж</h2><button className="text-btn" onClick={()=>p.navigate('garage')}>Керувати</button></div>{cars.length?cars.slice(0,3).map(c=><button className={'garage-mini '+(active?.id===c.id?'active':'')} key={c.id} onClick={()=>{setLookupVin('');if(command&&searchIntent(command.text).kind==='vin')setCommand(undefined);p.selectCar(c.id);}}><CarFront size={36}/><span><strong>{c.data.name}</strong><small>{c.data.year} · {Number(c.data.mileage||0).toLocaleString('uk-UA')} км</small></span><span className="garage-choice">{active?.id===c.id?'Обрано':'Обрати'}</span></button>):<p className="fine">Додайте авто за VIN — збережемо його у вашому гаражі.</p>}<button className="text-btn" onClick={()=>{setLookupVin('');p.selectCar('');setCommand({text:'',id:Date.now()});document.getElementById('finder-workspace')?.scrollIntoView({behavior:'smooth'});}}><Plus size={16}/>Додати авто</button></section><section className="dashboard-card service-shortcut"><MapPin size={30}/><h2>Сервіс на вашій вулиці</h2><p>СТО, контакти та маршрут від вашої адреси.</p><button className="outline-btn" onClick={()=>p.navigate('service')}>Знайти СТО <ArrowUpRight size={17}/></button></section></div>
 {offers.length>0&&<section className="recent-offers"><div className="section-top"><h2>З останнього пошуку</h2><button className="text-btn" onClick={()=>p.navigate('profile')}>Уся історія</button></div><div className="recent-offer-grid">{offers.slice(0,3).map((o:any)=><a href={o.url} target="_blank" rel="noopener noreferrer" className="dashboard-card" key={o.url}><Wrench size={27}/><small>{o.host}</small><h3>{o.title}</h3>{o.price&&<strong>{new Intl.NumberFormat('uk-UA',{style:'currency',currency:o.currency||'UAH'}).format(o.price)}</strong>}<small>Ціна з історії пошуку. Сумісність потребує перевірки.</small><span>Відкрити пропозицію ↗</span></a>)}</div></section>}
 <div id="finder-workspace"><VehicleFinder key={active?.id||'new'} save={p.save} records={p.records} signedIn={p.signedIn} initialCar={active} onVehicleChange={setPreview} onVinSearch={setLookupVin} command={command} onSearch={p.onSearch}/></div></div>;
}
