"use client";
import {Heart,Wrench,Trash2,ArrowUpRight,CarFront,UserRound} from 'lucide-react';
import type {RecordItem} from './data';
import type {SearchSession} from './vehicle-finder';
export function FavoritesPage({favorites,navigate,remove,guard,loading}:{favorites:RecordItem[];navigate:(s:string)=>void;remove:(r:RecordItem)=>void;guard:React.ReactNode;loading:boolean}){
 return <><div className="page-heading"><div><h1>Обране</h1><p>Збережені посилання на запчастини.</p></div><Heart size={30}/></div>{guard}{favorites.length?<div className="favorites-grid refreshed-favorites">{favorites.map(r=><article className="panel" key={r.id}><div className="section-top"><span className="personal-icon"><Wrench size={22}/></span><button className="icon-btn" aria-label={'Видалити з обраного: '+r.data.title} onClick={()=>remove(r)}><Trash2 size={16}/></button></div><h2>{r.data.title}</h2><p className="fine">{r.data.host||new URL(r.data.url).hostname}</p><p className="fine">{r.data.vehicle}</p>{r.data.price!=null&&<><strong className="offer-price">{new Intl.NumberFormat('uk-UA',{style:'currency',currency:r.data.currency||'UAH'}).format(r.data.price)}</strong><p className="fine">Ціна на момент збереження{r.data.checkedAt?' · '+new Date(r.data.checkedAt).toLocaleDateString('uk-UA'):''}</p></>}<a className="outline-btn full" href={r.data.url} target="_blank" rel="noopener noreferrer">Відкрити сайт <ArrowUpRight size={15}/></a></article>)}</div>:!loading&&<section className="panel empty-filter"><Heart size={40}/><h2>Збережіть потрібне на потім</h2><p>Знайдіть пропозиції та збережіть потрібні посилання.</p><button className="primary" onClick={()=>navigate('parts')}>Підібрати деталі</button></section>}</>;
}
export function ProfilePage({history,cars,expenses,guard,name,remove,navigate,repeatService}:{history:RecordItem[];cars:RecordItem[];expenses:RecordItem[];guard:React.ReactNode;name?:string;remove:(r:RecordItem)=>void;navigate:(s:string)=>void;repeatService:(s:SearchSession)=>void}){
 const total=expenses.reduce((sum,r)=>sum+Number(r.data.amount||0),0);
 return <><div className="page-heading"><div><h1>Особистий кабінет</h1><p>{name||'Ваш простір автовласника.'}</p></div><span className="personal-icon"><UserRound size={24}/></span></div>{guard}<div className="profile-stats">{[['Автомобілів',cars.length],['Пошуків',history.length],['Записів витрат',expenses.length],['Витрачено',total.toLocaleString('uk-UA')+' ₴']].map(([label,value])=><div className="panel" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><section className="panel"><div className="section-top"><h2>Історія пошуку</h2><span className="demo-label">{history.length} запитів</span></div>{history.length?history.map(h=><article className="history-search" key={h.id}><div><time className="fine" dateTime={new Date(h.created).toISOString()}>{new Date(h.created).toLocaleString('uk-UA')}</time><h3>{h.data.vehicle}</h3><p>{h.data.problem}</p><div className="history-part-tags">{(h.data.parts||[]).map((part:string)=><span key={part}>{part}</span>)}</div><div className="calculator-links">{(h.data.results||[]).map((r:any)=><a key={r.url} href={r.url} target="_blank" rel="noopener noreferrer">{r.title}{r.price!=null&&<strong> — {new Intl.NumberFormat('uk-UA',{style:'currency',currency:r.currency||'UAH'}).format(r.price)}</strong>}<ArrowUpRight size={15}/></a>)}</div><button className="outline-btn" onClick={()=>repeatService(h.data)}>Знайти СТО</button></div><button className="icon-btn" aria-label="Видалити пошук" onClick={()=>remove(h)}><Trash2 size={17}/></button></article>):<p className="fine">Тут з’являться ваші запити та знайдені посилання.</p>}</section><section className="panel profile-shortcuts"><h2>Швидкий доступ</h2><button onClick={()=>navigate('garage')}><CarFront size={24}/><span><strong>Мої автомобілі</strong><small>{cars.length} авто у гаражі</small></span><ArrowUpRight size={18}/></button><button onClick={()=>navigate('garage')}><Wrench size={24}/><span><strong>Обслуговування та витрати</strong><small>{total.toLocaleString('uk-UA')} ₴ всього</small></span><ArrowUpRight size={18}/></button></section>{name&&<a href="/signout-with-chatgpt?return_to=/" target="_top" className="outline-btn mt-4">Вийти</a>}</>;
}

