export function cleanIdentifier(value:string){return value.trim().toUpperCase().replace(/[\s-]/g,'');}
export const vehicleFields:Record<string,string>={Make:'Марка',Model:'Модель',ModelYear:'Рік',Trim:'Комплектація',Trim2:'Додаткова комплектація',Series:'Серія',BodyClass:'Кузов',VehicleType:'Тип авто',Doors:'Дверей',DisplacementL:'Об’єм двигуна, л',EngineModel:'Модель двигуна',EngineCylinders:'Циліндрів',EngineHP:'Потужність, к.с.',FuelTypePrimary:'Паливо',FuelTypeSecondary:'Додаткове паливо',TransmissionStyle:'Коробка передач',TransmissionSpeeds:'Кількість передач',DriveType:'Привід',ElectrificationLevel:'Електрифікація',PlantCountry:'Країна виробництва',PlantCity:'Місто виробництва',Manufacturer:'Виробник',GVWR:'Повна маса (категорія)',WheelBaseShort:'Колісна база, дюйми',Seats:'Місць',SeatRows:'Рядів сидінь',SteeringLocation:'Розташування керма',ABS:'ABS',ESC:'Стабілізація',AirBagLocFront:'Передні подушки',AirBagLocSide:'Бічні подушки'};
export type VehicleInfo={vin:string;make:string;model:string;year:string;engine:string;fields:{label:string;value:string}[];warning:string;source:string;checkedAt:string};
export function mapVehicle(raw:Record<string,string>,vin:string):VehicleInfo{
const fields=Object.entries(vehicleFields).flatMap(([key,label])=>{const value=String(raw[key]||'').trim();return value&&value!=='Not Applicable'? [{label,value}]:[]});
return {vin,make:raw.Make||'',model:raw.Model||'',year:raw.ModelYear||'',engine:[raw.DisplacementL?`${Number(raw.DisplacementL).toFixed(1)} л`:'',raw.EngineModel,raw.FuelTypePrimary].filter(Boolean).join(' · '),fields,warning:raw.ErrorCode&&raw.ErrorCode!=='0'?'Джерело повернуло часткове декодування. Перевірте VIN і звірте дані з техпаспортом.':'',source:'NHTSA vPIC',checkedAt:new Date().toISOString()};}
export const suggestions=[{match:/скрип|скрег|гальм|тормоз/i,parts:['Гальмівні колодки','Гальмівні диски'],note:'Причину шуму має підтвердити огляд гальм.'},{match:/стук|підвіск|ям|амортиз/i,parts:['Стійка стабілізатора','Амортизатор','Опора амортизатора'],note:'Стук може мати різні причини. Перед купівлею потрібна діагностика підвіски.'},{match:/не завод|не запуска|акум|стартер/i,parts:['Акумулятор','Стартер','Свічки запалювання'],note:'Спочатку перевірте заряд, контакти та результати діагностики.'},{match:/олив|масл|техобсл|\bто\b/i,parts:['Моторна олива','Масляний фільтр'],note:'Специфікацію оливи звірте з вимогами виробника двигуна.'},{match:/кондиціон|салон|запах/i,parts:['Фільтр салону'],note:'Фільтр — лише один із можливих напрямків перевірки.'}];
export function suggestParts(text:string){return suggestions.find(s=>s.match.test(text))||null;}
export function decodeEntities(s:string){return s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Math.min(Number(n),0x10ffff)));}
export function parseWebResults(html:string){const results:{title:string;url:string;host:string}[]=[];for(const match of html.matchAll(/<a\b([^>]*\bclass="result__a"[^>]*)>([\s\S]*?)<\/a>/g)){const href=match[1].match(/\bhref="([^"]+)"/)?.[1];if(!href)continue;try{const link=new URL(decodeEntities(href),'https://duckduckgo.com');const raw=link.hostname.endsWith('duckduckgo.com')?link.searchParams.get('uddg'):link.href;if(!raw)continue;const url=new URL(raw);if(url.protocol!=='https:'||url.username||url.password)continue;const host=url.hostname.toLowerCase();if(!/\.(ua|com)$/i.test(host)||/(youtube|facebook|wikipedia|instagram|duckduckgo)\./.test(host))continue;const title=decodeEntities(match[2].replace(/<[^>]*>/g,'')).trim();if(title&&!results.some(r=>r.url===url.href))results.push({title,url:url.href,host});}catch{}}return results.slice(0,10);}
