import {getChatGPTUser} from '@/app/chatgpt-auth';
import {storage} from '@/db/storage';
import {schemas} from '@/app/validation';
export const dynamic='force-dynamic';
const fail=(message:string,status=400)=>Response.json({error:message},{status});
export async function GET(){const user=await getChatGPTUser();if(!user)return fail('Увійдіть, щоб відкрити свій гараж.',401);try{const {db}=await storage();const rows=await db.prepare('SELECT id, kind, payload, created FROM records WHERE owner = ? ORDER BY created DESC').bind(user.userId).all();return Response.json({user:{name:user.displayName,email:user.email},records:rows.results.map((r:any)=>({id:r.id,kind:r.kind,data:JSON.parse(r.payload),created:r.created}))});}catch(e){console.error('records read',e);return fail('Не вдалося завантажити дані. Спробуйте ще раз.',503);}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return fail('Для збереження увійдіть в особистий простір.',401);if(request.headers.get('sec-fetch-site')==='cross-site')return fail('Недозволений запит.',403);try{const raw=await request.text();if(raw.length>60000)return fail('Завеликий запис.');const body=JSON.parse(raw);const schema=schemas[body.kind as keyof typeof schemas];if(!schema)return fail('Невідомий тип запису.');const parsed=schema.safeParse(body.data);if(!parsed.success)return fail('Перевірте заповнення полів.');const {db}=await storage();if(body.kind==='expense'||body.kind==='searchHistory'){const car=await db.prepare("SELECT id FROM records WHERE id = ? AND owner = ? AND kind = 'car'").bind(body.kind==='expense'?schemas.expense.parse(body.data).carId:schemas.searchHistory.parse(body.data).carId,user.userId).first();if(!car)return fail('Автомобіль не знайдено.',404);}
const id=crypto.randomUUID(),created=Date.now();await db.prepare('INSERT INTO records (id,owner,kind,payload,created) VALUES (?,?,?,?,?)').bind(id,user.userId,body.kind,JSON.stringify(parsed.data),created).run();return Response.json({record:{id,kind:body.kind,data:parsed.data,created}},{status:201});}catch(e){console.error('records save',e);return fail('Не вдалося зберегти. Ваші поля залишилися заповненими.',503);}}
export async function DELETE(request:Request){const user=await getChatGPTUser();if(!user)return fail('Потрібен вхід.',401);if(request.headers.get('sec-fetch-site')==='cross-site')return fail('Недозволений запит.',403);const id=new URL(request.url).searchParams.get('id');if(!id||!/^[a-f0-9-]{36}$/.test(id))return fail('Невірний запис.');try{const {db}=await storage();const row=await db.prepare('SELECT kind FROM records WHERE id = ? AND owner = ?').bind(id,user.userId).first();if(!row)return fail('Запис не знайдено.',404);if(row.kind==='car'){const expense=await db.prepare("SELECT id FROM records WHERE owner = ? AND kind = 'expense' AND json_extract(payload, '$.carId') = ? LIMIT 1").bind(user.userId,id).first();if(expense)return fail('Спершу видаліть записи витрат цього автомобіля.');}await db.prepare('DELETE FROM records WHERE id = ? AND owner = ?').bind(id,user.userId).run();return Response.json({ok:true});}catch(e){console.error('records delete',e);return fail('Не вдалося видалити. Спробуйте ще раз.',503);}}


export async function PATCH(request:Request){
 const user=await getChatGPTUser();if(!user)return fail('Потрібен вхід.',401);
 if(request.headers.get('sec-fetch-site')==='cross-site')return fail('Недозволений запит.',403);
 try{const raw=await request.text();if(raw.length>60000)return fail('Завеликий запис.');const body=JSON.parse(raw);if(typeof body.id!=='string')return fail('Невірний запис.');const {db}=await storage();const existing=await db.prepare('SELECT kind,created FROM records WHERE id = ? AND owner = ?').bind(body.id,user.userId).first();if(!existing)return fail('Запис не знайдено.',404);if(existing.kind!=='car')return fail('Редагування цього типу недоступне.');const parsed=schemas.car.safeParse(body.data);if(!parsed.success)return fail('Перевірте заповнення полів.');await db.prepare('UPDATE records SET payload = ? WHERE id = ? AND owner = ?').bind(JSON.stringify(parsed.data),body.id,user.userId).run();return Response.json({record:{id:body.id,kind:'car',data:parsed.data,created:existing.created}});
 }catch(e){console.error('records update',e);return fail('Не вдалося оновити автомобіль. Спробуйте ще раз.',503);}
}
